README.md

Updating typos in README.md

---

proxy-manager/rootfs/etc/cont-init.d/nginx.sh

Fix folder typo in sed command
None

🚑Fix typo in sed command

---

proxy-manager/Dockerfile

⬆Update node/npm to 10.16.3-r0

---

.gitlab-ci.yml
proxy-manager/Dockerfile
proxy-manager/build.json

Update base to 5.0.1 and OpenSSL to 1.1.1d-r0

Update base image/openssl version

---

proxy-manager/rootfs/etc/services.d/manager/run

:pencil2: Correct typo in code comment

---

LICENSE.md
README.md
proxy-manager/.README.j2
proxy-manager/DOCS.md

Happy New Year

---

proxy-manager/.README.j2

Small change to match the recent default branch renaming

Fix master->main in README template

---

proxy-manager/Dockerfile
proxy-manager/build.json

Upgrades the add-on base image to latest greatest

Upgrade add-on base image to 9.1.0

---

proxy-manager/config.json

Add missing port type to ports in ports & port description lists.
fixes #128

Add missing type to port definitions

---

proxy-manager/Dockerfile

Upgrades the NGINX Proxy Manager to v2.7.3

:arrow_up: Upgrades NGINX Proxy Manager to v2.7.3

---

proxy-manager/Dockerfile

:arrow_up: Upgrades py3-pip to 20.3.4-r0

---

proxy-manager/config.json

As the add-on needs more information about the networking environment.

Grant Supervisor API access to retreive environment information

---

proxy-manager/Dockerfile
proxy-manager/build.json

https://github.com/hassio-addons/addon-base/releases/tag/v9.1.2

Upgrade add-on base image to 9.1.2

---

proxy-manager/rootfs/etc/cont-init.d/mysql.sh

Update method to the newly implemented bashio function, so we don't remove other config.
Thought I should PR it as that's why I started on it in the first place :)

🔨 Change to addon.option for reset_database

---

proxy-manager/Dockerfile

:arrow_up: Upgrades git to 2.30.1-r0

---

proxy-manager/Dockerfile
proxy-manager/build.json

Upgrade add-on base image to 9.1.4
Also upgrades nodejs & openssl in order to match the upstream

Upgrade add-on base image to 9.1.4

---

proxy-manager/Dockerfile

:arrow_up: Upgrades python3 to 3.8.7-r1

---

proxy-manager/Dockerfile

:arrow_up: Upgrades nodejs to 14.16.0-r0

---

proxy-manager/Dockerfile
proxy-manager/build.json

Upgrades add-on base image to v9.1.5

:arrow_up: Upgrades add-on base image to v9.1.5

---

proxy-manager/Dockerfile

⬆️ Upgrades git to 2.30.2-r0

---

proxy-manager/Dockerfile

⬆️ Upgrades python3 to 3.8.8-r0

---

proxy-manager/Dockerfile

https://github.com/jc21/nginx-proxy-manager/releases/tag/v2.8.1

⬆️ Upgrades NGINX Proxy Manager to v2.8.1

---

proxy-manager/Dockerfile
proxy-manager/build.json

Upgrades openssl-dev to 1.1.1k-r0

⬆️ Upgrade add-on base image to 9.1.6

---

proxy-manager/Dockerfile

⬆️ Upgrades nodejs to 14.16.1-r0

---

proxy-manager/Dockerfile
proxy-manager/build.json

Upgrades add-on base image to v9.1.7

⬆️ Upgrades add-on base image to v9.1.7

---

proxy-manager/Dockerfile

⬆️ Upgrades nodejs to 14.16.1-r1

---

proxy-manager/Dockerfile
proxy-manager/build.json

Upgrades add-on base image to v9.2.0

Upgrades add-on base image to v9.2.0

---

proxy-manager/Dockerfile

⬆️ Upgrades mariadb to 10.5.9-r0

---

proxy-manager/Dockerfile
proxy-manager/build.json

Upgrades add-on base image to v10.0.1
This add-on probably needs to be migrated to Debian, but at this point, I'm making it work with Alpine first in order to make some CI changes (and make at least the build pass instead of being broken).

⬆️ Upgrades add-on base image to v10.0.1

---

proxy-manager/build.yaml
proxy-manager/config.yaml

Sign add-on with Codenotary Community Attestation Service (CAS)

:lock: Sign add-on with Codenotary Community Attestation Service (CAS)

---

proxy-manager/Dockerfile
proxy-manager/rootfs/etc/services.d/manager/finish

Bumps it to the latest version. Needs other changes; but will work from here.

⬆️ Upgrades NGINX Proxy Manager to v2.9.18

---

proxy-manager/Dockerfile
proxy-manager/rootfs/etc/cont-init.d/mysql.sh
proxy-manager/rootfs/etc/fix-attrs.d/permissions

This older migration path is from when the database was running inside the add-on. This has not been the case for years; time for this migration path to go.

:broom: Clean up old migration path

---

proxy-manager/Dockerfile

The newer version of NPM uses this; so better get this added to get all dependencies working.

Add logrotate

---

LICENSE.md
README.md
proxy-manager/.README.j2
proxy-manager/DOCS.md

Small tweaks: Adding my button; update to license year

:books: Documentation tweaks and updates

---

proxy-manager/Dockerfile
proxy-manager/build.yaml

Upgrades add-on base image to 12.2.3

⬆️ Upgrades add-on base image to 12.2.3

---

proxy-manager/Dockerfile
proxy-manager/build.yaml

⬆️ Upgrades add-on base image to 12.2.4

---

proxy-manager/Dockerfile

⬆️ Upgrades git to 2.36.3-r0

---

proxy-manager/Dockerfile

⬆️ Upgrades openssl to 1.1.1s-r0

---

proxy-manager/Dockerfile

⬆️ Upgrades python3 to 3.10.8-r0

---

proxy-manager/Dockerfile

⬆️ Upgrades nodejs to 16.17.1-r0

---

proxy-manager/Dockerfile

⬆️ Upgrades mariadb-client to 10.6.10-r0

---

proxy-manager/Dockerfile

⬆️ Upgrades nginx to 1.22.1-r0

---

proxy-manager/Dockerfile
proxy-manager/build.yaml

⬆️ Upgrades add-on base image to 12.2.7

---

proxy-manager/config.yaml

Exclude logs from backups.
fixes #108

🚑 Exclude logs from backup

---

proxy-manager/Dockerfile

https://github.com/NginxProxyManager/nginx-proxy-manager/releases/tag/v2.9.19

⬆️ Upgrades NGINX Proxy Manager to v2.9.19

---

LICENSE.md
README.md
proxy-manager/.README.j2
proxy-manager/DOCS.md

:fireworks: Updates maintenance/license year to 2023

---

proxy-manager/DOCS.md

> (Describe the changes and rationale behind them)
Fixes a broken URL in the documentation.
> ([Github link][autolink-references] to related issues or pull requests)
[autolink-references]: https://help.github.com/articles/autolinked-references-and-urls/

Fix broken URL

---

proxy-manager/Dockerfile

Upstream project changed to user `npm` in their containers, we remain with the old structure.

Clean up upstream user

---

proxy-manager/Dockerfile

Remove mariadb dependencies

---

README.md
proxy-manager/build.yaml
proxy-manager/config.yaml

Drop support for armhf & i386

---

proxy-manager/rootfs/etc/s6-overlay/s6-rc.d/init-npm/up

Fix copy paste error in npm init script

---

LICENSE.md
README.md
proxy-manager/.README.j2
proxy-manager/DOCS.md

Prepares documentation for the upcoming update.
- Happy New Year 🍾  (updates maintenance year)
- Remove limitation for streams. They have been unlocked (still useless, but knock yourself out 🤷 )
- Port 80 is optional, as DNS challenges can be used nowadays instead

Update documentation for upcoming release

---

LICENSE.md
README.md
proxy-manager/.README.j2
proxy-manager/DOCS.md

:fireworks: Updates maintenance/license year to 2025
